### PR TITLE
another speedup, cleanup

### PR DESCRIPTION
**Pull request by mdsumner**

### CODE REVIEW

**Comment by mdsumner** [comment]
Hopefully this goes ok, I merged master into mine just now so this should PR ok. 

I'm out until next week, cu

**Comment by mdsumner** [comment]
ping @mpadge - I don't know why this PR is so messy, I might just can it and fold in manually

**Comment by mpadge** [comment]
All good, it was just a couple of tiny conflicts that I fixed and merged - thanks!

**Comment by mdsumner** [comment]
cool, btw totally interested in the serial polyclip method it's very likely faster - the triangulate everything approach is useful for much more general tasks - and is like an uber hammer. Also I got to clean up a bunch of things that will go back into spacebucket -or whatever sensible thing replaces it.

**Comment by mpadge** [comment]
Now that concaveman is bundled, the polyclipping idea should be fairly straightforward, and would be great to implement. I will nevertheless probably delay until it becomes clear what's going to happen with the submission ...

**Pull request merged**
